services:
  list-db:
    image: mysql:latest
    container_name: listsdb
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: listdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
