services:
  list-db:
    image: mysql:latest
    volumes:
      - my-db-volume:/var/lib/mysql
    container_name: listsdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: listdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
volumes:
  my-db-volume: